image: jpetazzo/dind

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker pull $IMAGE_TAG:builder-latest || true
    - docker build --pull
                   --cache-from $IMAGE_TAG:builder-latest
                   --tag $IMAGE_TAG:builder-latest
                   --target builder 
                   .
    - docker push $IMAGE_TAG:builder-latest
  retry: 2

test01:
  stage: test
  script:
    - apt-get update && apt-get install -y --no-install-recommends xvfb
    - docker pull $IMAGE_TAG:builder-latest
    - xvfb-run --error-file error.log -f "/tmp/.docker.xauth" --server-args="-screen 0 1280x1024x16" ./run.sh $IMAGE_TAG:builder-latest ./ctp2 &
    - sleep 10
    - killall Xvfb
