image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker pull $IMAGE_TAG:system-latest || true
    - docker pull $IMAGE_TAG:builder-latest || true
    - docker pull $IMAGE_TAG:test || true
    ## 1st stage build using system-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --tag $IMAGE_TAG:system-latest
                   --target system
                   .
    ## 2nd stage build using builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --cache-from $IMAGE_TAG:builder-latest
                   --tag $IMAGE_TAG:builder-latest
                   --target builder 
                   .
    ## 3rd stage build using system-latest and builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --cache-from $IMAGE_TAG:builder-latest
                   --cache-from $IMAGE_TAG:test
                   --tag $IMAGE_TAG:test
                   .
    - docker push $IMAGE_TAG:system-latest
    - docker push $IMAGE_TAG:builder-latest
    - docker push $IMAGE_TAG:test
  retry: 2

.test: &test
  stage: test
  image: registry.gitlab.com/lynxabraxas/dind-sikuli/master:latest
  artifacts:
    paths:
    - ${CI_JOB_NAME}.png
  script:
    - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
    - mkdir -p ${SHARED_PATH}/.X11-unix/
    - mkdir -p /tmp/.X11-unix/
    - mount --bind ${SHARED_PATH}/.X11-unix/ /tmp/.X11-unix/
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - pidX=$!
    - sleep 3
    - docker pull $IMAGE_TAG:test
    - docker run
             --env DISPLAY
             -v ${SHARED_PATH}/.X11-unix/:/tmp/.X11-unix/
             -v $(pwd)/.civctp2/save/:/opt/ctp2/ctp2_program/ctp/save/
             $IMAGE_TAG:test
             ./ctp2 nointromovie &
    - pidD=$!
    - java -cp "/opt/sikulixapi.jar:/opt/jython-standalone-2.7.1.jar" org.python.util.jython tests/${CI_JOB_NAME}.sikuli/${CI_JOB_NAME}.py
    - kill $pidD
    - kill $pidX
    - test -f ${CI_JOB_NAME}.png
  retry: 2

start-game: *test
new-game:   *test
load-game:  *test

release:
  variables:
    GIT_STRATEGY: none
  stage: release
  script:
    - docker pull $IMAGE_TAG:test
    - docker tag  $IMAGE_TAG:test $IMAGE_TAG:latest
    - docker push $IMAGE_TAG:latest
  only:
    - master
