image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker pull $IMAGE_TAG:system-latest || true
    - docker pull $IMAGE_TAG:builder-latest || true
    - docker pull $IMAGE_TAG:test || true
    ## 1st stage build using system-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --tag $IMAGE_TAG:system-latest
                   --target system
                   .
    ## 2nd stage build using builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --cache-from $IMAGE_TAG:builder-latest
                   --tag $IMAGE_TAG:builder-latest
                   --target builder 
                   .
    ## 3rd stage build using system-latest and builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --cache-from $IMAGE_TAG:builder-latest
                   --cache-from $IMAGE_TAG:test
                   --tag $IMAGE_TAG:test
                   .
    - docker push $IMAGE_TAG:system-latest
    - docker push $IMAGE_TAG:builder-latest
    - docker push $IMAGE_TAG:test
  retry: 2

test:ss_start:
  stage: test
  image: registry.gitlab.com/lynxabraxas/dind-sikuli/master:latest
  artifacts:
    paths:
    - ctp2start.png
  script:
    - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
    - mkdir -p ${SHARED_PATH}/.X11-unix/
    - mkdir -p /tmp/.X11-unix/
    - mount --bind ${SHARED_PATH}/.X11-unix/ /tmp/.X11-unix/
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - pidX=$!
    - sleep 3
    - docker pull $IMAGE_TAG:test
    - docker run --env DISPLAY -v ${SHARED_PATH}/.X11-unix/:/tmp/.X11-unix/ $IMAGE_TAG:test ./ctp2 nointromovie &
    - pidD=$!
    - java -cp "/opt/sikulixapi.jar:/opt/jython-standalone-2.7.1.jar" org.python.util.jython tests/start-game.sikuli/start-game.py
    - kill $pidD
    - kill $pidX
    - test -f ctp2start.png
  retry: 2

test:ss_new:
  stage: test
  image: registry.gitlab.com/lynxabraxas/dind-sikuli/master:latest
  artifacts:
    paths:
    - ctp2new-game.png
  script:
    - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
    - mkdir -p ${SHARED_PATH}/.X11-unix/
    - mkdir -p /tmp/.X11-unix/
    - mount --bind ${SHARED_PATH}/.X11-unix/ /tmp/.X11-unix/
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - pidX=$!
    - sleep 3
    - docker pull $IMAGE_TAG:test
    - docker run --env DISPLAY -v ${SHARED_PATH}/.X11-unix/:/tmp/.X11-unix/ -v $(pwd)/.civctp2/userprofile.txt:/opt/ctp2/ctp2_program/ctp/userprofile.txt -v $(pwd)/.civctp2/save/:/opt/ctp2/ctp2_program/ctp/save/ $IMAGE_TAG:test ./ctp2 nointromovie &
    - pidD=$!
    - java -cp "/opt/sikulixapi.jar:/opt/jython-standalone-2.7.1.jar" org.python.util.jython tests/new-game.sikuli/new-game.py
    - kill $pidD
    - kill $pidX
    - test -f ctp2new-game.png
  retry: 2

test:ss_load:
  stage: test
  image: registry.gitlab.com/lynxabraxas/dind-sikuli/master:latest
  artifacts:
    paths:
    - ctp2load-game.png
  script:
    - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
    - mkdir -p ${SHARED_PATH}/.X11-unix/
    - mkdir -p /tmp/.X11-unix/
    - mount --bind ${SHARED_PATH}/.X11-unix/ /tmp/.X11-unix/
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - pidX=$!
    - sleep 3
    - docker pull $IMAGE_TAG:test
    - docker run --env DISPLAY -v ${SHARED_PATH}/.X11-unix/:/tmp/.X11-unix/ -v $(pwd)/.civctp2/userprofile.txt:/opt/ctp2/ctp2_program/ctp/userprofile.txt -v $(pwd)/.civctp2/save/:/opt/ctp2/ctp2_program/ctp/save/ $IMAGE_TAG:test ./ctp2 nointromovie &
    - pidD=$!
    - java -cp "/opt/sikulixapi.jar:/opt/jython-standalone-2.7.1.jar" org.python.util.jython tests/load-game.sikuli/load-game.py
    - kill $pidD
    - kill $pidX
    - test -f ctp2load-game.png
  retry: 2

release:
  variables:
    GIT_STRATEGY: none
  stage: release
  script:
    - docker pull $IMAGE_TAG:test
    - docker tag  $IMAGE_TAG:test $IMAGE_TAG:latest
    - docker push $IMAGE_TAG:latest
  only:
    - master
