image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test:ss
  - test:co
  - release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker pull $IMAGE_TAG:system-latest || true
    - docker pull $IMAGE_TAG:builder-latest || true
    - docker pull $IMAGE_TAG:test || true
    ## 1st stage build using system-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --tag $IMAGE_TAG:system-latest
                   --target system
                   .
    ## 2nd stage build using builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --cache-from $IMAGE_TAG:builder-latest
                   --tag $IMAGE_TAG:builder-latest
                   --target builder 
                   .
    ## 3rd stage build using system-latest and builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:system-latest
                   --cache-from $IMAGE_TAG:builder-latest
                   --cache-from $IMAGE_TAG:test
                   --tag $IMAGE_TAG:test
                   .
    - docker push $IMAGE_TAG:system-latest
    - docker push $IMAGE_TAG:builder-latest
    - docker push $IMAGE_TAG:test
  retry: 2

test:ss_start:
  stage: test:ss
  artifacts:
    paths:
    - ctp2start.png
  script:
    - apk update && apk upgrade && apk add --no-cache xvfb imagemagick
    - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
    - mkdir -p ${SHARED_PATH}/.X11-unix/
    - mkdir -p /tmp/.X11-unix/
    - mount --bind ${SHARED_PATH}/.X11-unix/ /tmp/.X11-unix/
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - pidX=$!
    - sleep 3
    - docker pull $IMAGE_TAG:test
    - docker run --env DISPLAY -v ${SHARED_PATH}/.X11-unix/:/tmp/.X11-unix/ $IMAGE_TAG:test ./ctp2 &
    - pidD=$!
    - sleep 10
    - import -window root ctp2start.png
    - kill $pidD
    - kill $pidX
  retry: 2

test:co_start:
  stage: test:co
  dependencies:
    - test:ss_start
  script:
    - apk update && apk upgrade && apk add --no-cache imagemagick
    - compare -metric rmse ctp2start.png comp/ctp2start.png 'null:' 2>&1 | tee /dev/stderr | grep '0 (0)'

test:ss_new:
  stage: test:ss
  image: registry.gitlab.com/lynxabraxas/dind-sikuli/master:latest
  artifacts:
    paths:
    - ctp2new-game.png
  script:
    - apk update && apk upgrade && apk add --no-cache xvfb
    - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
    - mkdir -p ${SHARED_PATH}/.X11-unix/
    - mkdir -p /tmp/.X11-unix/
    - mount --bind ${SHARED_PATH}/.X11-unix/ /tmp/.X11-unix/
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - pidX=$!
    - sleep 3
    - docker pull $IMAGE_TAG:test
    - docker run --env DISPLAY -v ${SHARED_PATH}/.X11-unix/:/tmp/.X11-unix/ $IMAGE_TAG:test ./ctp2 &
    - pidD=$!
    - 'java -jar /opt/sikulix.jar -r tests/new-game.sikuli/ | grep "\[info\] Exit code: 0"'
    - kill $pidD
    - kill $pidX
  retry: 2

release:
  variables:
    GIT_STRATEGY: none
  stage: release
  script:
    - docker pull $IMAGE_TAG:test
    - docker tag  $IMAGE_TAG:test $IMAGE_TAG:latest
    - docker push $IMAGE_TAG:latest
  only:
    - master
